version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prisma-test-integration
    restart: always
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
volumes:
  postgres:
